- hosts: all
  become: yes
  vars_files:
    - variaveis.yml
  tasks:
  - import_role:
      name: mysql
    when: ansible_hostname == 'database'
  - import_role:
      name: webserver
    when: ansible_hostname.startswith('webserver')
  - import_role:
      name: haproxy
    when: ansible_hostname == 'balancer'
