- hosts: all
  become: yes
  vars_files:
    - ~/Vagrant/live/ansible/single-file/variaveis.yml
  tasks:
  - block:
    - name: Instalando pacotes do Webserver
      apt:
        name: ["lighttpd", "php-fpm", "php-mysql", "php-memcached", "memcached", "git"]
        state: present
    - name: Copiando arquivos de configuração
      template:
        src: "{{ item.split('|')[0] }}"
        dest: "{{ item.split('|')[1] }}"
      loop:
      - "~/Vagrant/live/ansible/single-file/confs/15-php-fpm.conf|/etc/lighttpd/conf-available/15-php-fpm.conf"
      - "~/Vagrant/live/ansible/single-file/confs/www.conf|/etc/php/7.3/fpm/pool.d/www.conf"
      - "~/Vagrant/live/ansible/single-file/confs/memcached.conf|/etc/memcached.conf"
    - name: Carregando módulos do lighttpd
      command: lighty-enable-mod php-fpm
      ignore_errors: yes
    - name: Instalando site
      git:
        repo: https://github.com/hector-vido/php-ms.git
        dest: /tmp/html
        depth: 1
        force: yes
    - name: Movendo site
      copy:
        src: /tmp/html
        dest: /var/www/
        remote_src: yes
    - name: Reiniciando serviços
      service:
        name: '{{ item }}'
        state: restarted
      loop:
      - memcached
      - php7.3-fpm
      - lighttpd
    when: ansible_hostname.startswith('webserver')
  - block:
    - name: Instalando pacotes do Banco de Dados
      apt:
        name: ["mariadb-server"]
        state: present
    - name: Copiando dump inicial
      template:
        src: "{{ item.split('|')[0] }}"
        dest: "{{ item.split('|')[1] }}"
      loop:
      - "~/Vagrant/live/ansible/single-file/confs/database.sql|/tmp"
      - "~/Vagrant/live/ansible/single-file/confs/50-server.cnf|/etc/mysql/mariadb.conf.d"
    - shell: mysql < /tmp/database.sql
    when: ansible_hostname == 'database'
  - block:
    - name: Instalando HAProxy
      apt:
        name: haproxy
        state: present
    - name: Copiando arquivo de configuração
      template:
        src: ~/Vagrant/live/ansible/single-file/confs/haproxy.cfg
        dest: /etc/haproxy/
    - name: Recarregando HaProxy
      service:
        name: haproxy
        state: reloaded
    when: ansible_hostname == 'balancer'
